### ISSUE TITLE
Sistemas en UTN BA

### ISSUE THREAD

**Issue by Agustoledo10** [pdepjm/2023-tp0-presentacion-nicolasizraelski#1]
Como andas nico? Che me parecio medio raro que aclares que estudias sistemas en utn ya que es presentacion de una materia de la carrera jajaja, yo lo sacaria, alta presentacion igual :)

**Comment by nicolasizraelski** [comment]
Tenés razón jaja. Estaba probando Markdown y ni le presté atención a lo que había escrito. Gracias por el comentario
